"""Tests for release-facing action metadata."""

from __future__ import annotations

import re
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
ACTION_PATH = REPO_ROOT / "action.yml"
README_PATH = REPO_ROOT / "README.md"
REFERENCE_PATH = REPO_ROOT / "docs" / "reference.md"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
PAYLOAD_SCHEMA_PATH = REPO_ROOT / "PAYLOAD_SCHEMA.md"


def _project_version() -> str:
    pyproject = PYPROJECT_PATH.read_text(encoding="utf-8")
    match = re.search(r'^version = "([^"]+)"$', pyproject, re.MULTILINE)
    assert match, "pyproject.toml is missing a project version"
    return match.group(1)


def test_action_uses_moving_minor_image_tag() -> None:
    action = yaml.safe_load(ACTION_PATH.read_text(encoding="utf-8"))
    assert action["runs"]["using"] == "docker"
    assert action["runs"]["image"] == "docker://ghcr.io/ml-ci-labs/ml-ci-action:v0.4"


def test_release_facing_versions_are_consistent() -> None:
    version = _project_version()
    readme = README_PATH.read_text(encoding="utf-8")
    reference = REFERENCE_PATH.read_text(encoding="utf-8")
    action_refs = re.findall(r"ml-ci-labs/ml-ci-action@v\d+\.\d+\.\d+", readme)

    assert action_refs
    assert set(action_refs) == {f"ml-ci-labs/ml-ci-action@v{version}"}
    assert "Generated by [ML-CI](https://github.com/ml-ci-labs/ml-ci-action) v" not in reference


def test_action_metadata_exposes_sprint_5_contract() -> None:
    action = yaml.safe_load(ACTION_PATH.read_text(encoding="utf-8"))

    assert "report-mode" in action["inputs"]
    assert "baseline-ref" in action["inputs"]
    assert "baseline-path" in action["inputs"]
    assert "upload-url" in action["inputs"]
    assert "upload-token" in action["inputs"]
    assert "report-markdown-path" in action["outputs"]
    assert "report-json-path" in action["outputs"]
    assert "app-connected" in action["outputs"]


def test_payload_schema_document_exists() -> None:
    assert PAYLOAD_SCHEMA_PATH.exists()
