"""Model card generation using Hugging Face hub."""

from __future__ import annotations

from typing import TYPE_CHECKING

from huggingface_hub import ModelCard, ModelCardData

if TYPE_CHECKING:
    from src.utils.metrics import MetricComparison, MetricsData


def generate_model_card(
    metrics_data: MetricsData,
    comparisons: list[MetricComparison] | None = None,
    output_path: str = "MODEL_CARD.md",
) -> str:
    """Generate a model card from training metrics and save to disk.

    Args:
        metrics_data: Current model metrics and metadata.
        comparisons: Optional metric comparisons against baseline.
        output_path: File path to save the model card.

    Returns:
        The output_path where the card was saved.
    """
    # Build card data
    card_data = ModelCardData(
        language="en",
        library_name=metrics_data.framework if metrics_data.framework != "unknown" else None,
        tags=["ml-ci", "auto-generated"],
    )

    # Build the model card content manually for more control
    sections: list[str] = []

    # Header
    sections.append(f"# {metrics_data.model_name}")
    sections.append("")
    sections.append(f"*Auto-generated by ML-CI on {metrics_data.timestamp or 'N/A'}*")
    sections.append("")

    # Model details
    sections.append("## Model Details")
    sections.append("")
    sections.append(f"- **Model name**: {metrics_data.model_name}")
    sections.append(f"- **Framework**: {metrics_data.framework}")
    if metrics_data.timestamp:
        sections.append(f"- **Training date**: {metrics_data.timestamp}")
    sections.append("")

    # Dataset
    if metrics_data.dataset:
        sections.append("## Training Data")
        sections.append("")
        ds = metrics_data.dataset
        if "name" in ds:
            sections.append(f"- **Dataset**: {ds['name']}")
        if "version" in ds:
            sections.append(f"- **Version**: {ds['version']}")
        if "num_samples" in ds:
            sections.append(f"- **Samples**: {ds['num_samples']:,}")
        for key, value in ds.items():
            if key not in ("name", "version", "num_samples"):
                sections.append(f"- **{key}**: {value}")
        sections.append("")

    # Hyperparameters
    if metrics_data.hyperparameters:
        sections.append("## Hyperparameters")
        sections.append("")
        sections.append("| Parameter | Value |")
        sections.append("|-----------|-------|")
        for param, value in sorted(metrics_data.hyperparameters.items()):
            sections.append(f"| {param} | {value} |")
        sections.append("")

    # Evaluation results
    sections.append("## Evaluation Results")
    sections.append("")

    if comparisons:
        sections.append("| Metric | Baseline | Current | Change |")
        sections.append("|--------|----------|---------|--------|")
        for comp in comparisons:
            sign = "+" if comp.delta > 0 else ""
            sections.append(
                f"| {comp.name} | {comp.baseline:.4f} | {comp.current:.4f} | {sign}{comp.delta:.4f} |"
            )
    else:
        sections.append("| Metric | Value |")
        sections.append("|--------|-------|")
        for name, value in sorted(metrics_data.metrics.items()):
            sections.append(f"| {name} | {value:.4f} |")

    sections.append("")

    # Intended use
    sections.append("## Intended Use")
    sections.append("")
    sections.append("*Please fill in the intended use cases for this model.*")
    sections.append("")

    # Limitations
    sections.append("## Limitations")
    sections.append("")
    sections.append("*Please document known limitations and biases.*")
    sections.append("")

    # Footer
    sections.append("---")
    sections.append("*This model card was auto-generated by [ML-CI](https://github.com/ml-ci/ml-ci-action). ")
    sections.append("Please review and complete the sections marked with italics.*")

    content = "\n".join(sections)

    # Use ModelCard to handle frontmatter
    card = ModelCard(content)
    card.data = card_data
    card.save(output_path)

    return output_path
