"""GitHub PR comment generation and posting."""

from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING

import requests

from src.utils.metrics import MetricComparison

if TYPE_CHECKING:
    from src.validators.data_validator import DataValidationResult
    from src.validators.model_validator import ModelValidationResult

COMMENT_MARKER = "<!-- ml-ci-report -->"
VERSION = "0.1.0"


def generate_report(
    model_result: ModelValidationResult | None = None,
    data_result: DataValidationResult | None = None,
    model_card_path: str | None = None,
) -> str:
    """Build a full markdown validation report for a PR comment.

    Args:
        model_result: Model validation result (can be None if no baseline).
        data_result: Data validation result (can be None if no data checks).
        model_card_path: Path to generated model card (can be None).

    Returns:
        Markdown string for the PR comment.
    """
    sections: list[str] = [COMMENT_MARKER, ""]

    # Header
    if model_result and model_result.regression_result.regression_detected:
        sections.append("## :x: ML-CI Validation Report")
    elif data_result and not data_result.overall_passed:
        sections.append("## :warning: ML-CI Validation Report")
    else:
        sections.append("## :white_check_mark: ML-CI Validation Report")

    sections.append("")

    # Model Performance section
    if model_result:
        sections.append("### Model Performance")
        sections.append("")
        sections.append(f"**Model**: `{model_result.model_name}` ({model_result.framework})")
        sections.append("")

        if model_result.comparisons:
            sections.append(_build_metrics_table(model_result.comparisons))
            sections.append("")

        # Regression test result
        rr = model_result.regression_result
        sections.append(f"**Regression test**: `{rr.method}` (tolerance: {rr.details.get('tolerance', 0):.1%})")
        if rr.regression_detected:
            sections.append(f"**Result**: :x: {rr.details.get('regressed_count', 0)} metric(s) regressed")
        else:
            sections.append("**Result**: :white_check_mark: All metrics within tolerance")
        sections.append("")

        # New/removed metrics
        if model_result.current_only_metrics:
            sections.append(
                f"**New metrics** (not in baseline): {', '.join(f'`{m}`' for m in model_result.current_only_metrics)}"
            )
        if model_result.baseline_only_metrics:
            sections.append(
                f"**Removed metrics** (not in current): {', '.join(f'`{m}`' for m in model_result.baseline_only_metrics)}"
            )
        if model_result.current_only_metrics or model_result.baseline_only_metrics:
            sections.append("")

    # Data Quality section
    if data_result:
        sections.append("### Data Quality")
        sections.append("")
        sections.append(_build_data_quality_section(data_result))
        sections.append("")

    # Model Card section
    if model_card_path:
        sections.append("### Model Card")
        sections.append("")
        sections.append(f"Model card generated at `{model_card_path}`")
        sections.append("")

    # Summary
    sections.append("### Summary")
    sections.append("")
    if model_result:
        sections.append(f"- {model_result.summary}")
    if data_result:
        status = ":white_check_mark: Passed" if data_result.overall_passed else ":x: Failed"
        sections.append(f"- Data quality: {status}")
    sections.append("")

    # Footer
    sections.append("---")
    sections.append(f"*Generated by [ML-CI](https://github.com/ml-ci/ml-ci-action) v{VERSION}*")

    return "\n".join(sections)


def _build_metrics_table(comparisons: list[MetricComparison]) -> str:
    """Build a GitHub-flavored markdown table from metric comparisons."""
    lines: list[str] = []
    lines.append("| Metric | Baseline | Current | Delta | Delta % | Status |")
    lines.append("|--------|----------|---------|-------|---------|--------|")

    for comp in comparisons:
        # Format values
        baseline_str = _fmt_metric(comp.baseline)
        current_str = _fmt_metric(comp.current)
        delta_str = _fmt_delta(comp.delta)
        pct_str = _fmt_pct(comp.delta_pct, comp.higher_is_better)

        # Status emoji
        if comp.regression:
            status = ":x:"
        elif comp.improved and comp.delta != 0:
            status = ":white_check_mark:"
        elif comp.delta == 0:
            status = ":heavy_minus_sign:"
        else:
            status = ":warning:"  # degraded but within tolerance

        lines.append(
            f"| {comp.name} | {baseline_str} | {current_str} | {delta_str} | {pct_str} | {status} |"
        )

    return "\n".join(lines)


def _build_data_quality_section(data_result: DataValidationResult) -> str:
    """Build a data quality summary section."""
    lines: list[str] = []

    # Schema
    if data_result.schema_valid:
        lines.append("- :white_check_mark: Schema validation passed")
    else:
        lines.append("- :x: Schema validation failed")
        for err in data_result.schema_errors[:5]:  # limit to 5 errors
            lines.append(f"  - {err}")

    # Missing values
    high_missing = {
        col: pct for col, pct in data_result.missing_value_report.items() if pct > 0.05
    }
    if high_missing:
        lines.append(f"- :warning: {len(high_missing)} column(s) with >5% missing values")
        for col, pct in sorted(high_missing.items(), key=lambda x: -x[1])[:5]:
            lines.append(f"  - `{col}`: {pct:.1%} missing")
    else:
        lines.append("- :white_check_mark: No columns with >5% missing values")

    # Duplicates
    if data_result.duplicate_count > 0:
        lines.append(
            f"- :warning: {data_result.duplicate_count} duplicate rows "
            f"({data_result.duplicate_pct:.1%} of data)"
        )
    else:
        lines.append("- :white_check_mark: No duplicate rows")

    # Drift
    if data_result.drift_scores is not None:
        drifted = {col: psi for col, psi in data_result.drift_scores.items() if psi > 0.1}
        if drifted:
            lines.append(f"- :warning: Distribution drift detected in {len(drifted)} column(s)")
            for col, psi in sorted(drifted.items(), key=lambda x: -x[1])[:5]:
                lines.append(f"  - `{col}`: PSI = {psi:.3f}")
        else:
            lines.append("- :white_check_mark: No significant distribution drift")

    return "\n".join(lines)


def _fmt_metric(value: float) -> str:
    """Format a metric value for display."""
    if abs(value) >= 1000:
        return f"{value:,.2f}"
    if abs(value) < 0.001 and value != 0:
        return f"{value:.2e}"
    return f"{value:.4f}"


def _fmt_delta(delta: float) -> str:
    """Format a delta value with +/- sign."""
    if delta == 0:
        return "0"
    sign = "+" if delta > 0 else ""
    return f"{sign}{_fmt_metric(delta)}"


def _fmt_pct(pct: float, higher_is_better: bool) -> str:
    """Format a percentage change."""
    if pct == 0:
        return "0%"
    if abs(pct) == float("inf"):
        return "N/A"
    sign = "+" if pct > 0 else ""
    return f"{sign}{pct:.1%}"


def post_or_update_comment(
    repo: str,
    pr_number: int,
    body: str,
    token: str,
) -> None:
    """Post a new PR comment or update an existing one.

    Searches for an existing comment containing COMMENT_MARKER to avoid
    flooding the PR with duplicate reports on re-runs.

    Args:
        repo: Repository in "owner/repo" format.
        pr_number: Pull request number.
        body: Markdown comment body.
        token: GitHub token with pull-requests:write permission.
    """
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    base_url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    # Search for existing ML-CI comment
    existing_comment_id = None
    page = 1
    while True:
        resp = requests.get(
            base_url,
            headers=headers,
            params={"per_page": 100, "page": page},
            timeout=30,
        )
        resp.raise_for_status()
        comments = resp.json()
        if not comments:
            break

        for comment in comments:
            if COMMENT_MARKER in comment.get("body", ""):
                existing_comment_id = comment["id"]
                break

        if existing_comment_id is not None:
            break
        page += 1

    # Update or create
    if existing_comment_id:
        url = f"https://api.github.com/repos/{repo}/issues/comments/{existing_comment_id}"
        resp = requests.patch(url, headers=headers, json={"body": body}, timeout=30)
        resp.raise_for_status()
        print(f"::notice::Updated existing ML-CI comment (id: {existing_comment_id})")
    else:
        resp = requests.post(base_url, headers=headers, json={"body": body}, timeout=30)
        resp.raise_for_status()
        print(f"::notice::Posted new ML-CI comment on PR #{pr_number}")


def get_pr_number() -> int | None:
    """Extract the PR number from the GitHub Actions event payload.

    Returns:
        PR number, or None if not running in a PR context.
    """
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        return None

    try:
        with open(event_path) as f:
            event = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None

    # pull_request event
    if "pull_request" in event:
        return event["pull_request"].get("number")

    # issue_comment event (for /rerun type triggers)
    if "issue" in event and "pull_request" in event.get("issue", {}):
        return event["issue"].get("number")

    return None
