"""GitHub PR comment generation and posting."""

from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING, Any

import requests

from src.utils.metrics import MetricComparison

if TYPE_CHECKING:
    from src.validators.data_validator import DataValidationResult
    from src.validators.model_validator import ModelValidationResult

COMMENT_MARKER = "<!-- ml-ci-report -->"
PROJECT_URL = "https://github.com/ml-ci-labs/ml-ci-action"


def generate_report(
    model_result: ModelValidationResult | None = None,
    data_result: DataValidationResult | None = None,
    model_card_path: str | None = None,
    current_metrics: dict[str, float] | None = None,
    current_only_metrics: list[str] | None = None,
    baseline_only_metrics: list[str] | None = None,
    baseline_source: dict[str, Any] | None = None,
) -> str:
    """Build a full markdown validation report for a PR comment.

    Args:
        model_result: Model validation result (can be None if no baseline).
        data_result: Data validation result (can be None if no data checks).
        model_card_path: Path to generated model card (can be None).

    Returns:
        Markdown string for the PR comment.
    """
    sections: list[str] = [COMMENT_MARKER, ""]

    # Header
    data_failures = data_result.failure_count if data_result else 0
    data_warnings = data_result.warning_count if data_result else 0
    if model_result and model_result.blocking_regression_count > 0:
        sections.append("## :x: ML-CI Validation Report")
    elif data_failures > 0:
        sections.append("## :x: ML-CI Validation Report")
    elif model_result and model_result.warning_regression_count > 0:
        sections.append("## :warning: ML-CI Validation Report")
    elif data_warnings > 0:
        sections.append("## :warning: ML-CI Validation Report")
    else:
        sections.append("## :white_check_mark: ML-CI Validation Report")

    sections.append("")

    # Model Performance section
    if model_result:
        sections.append("### Model Performance")
        sections.append("")
        sections.append(f"**Model**: `{model_result.model_name}` ({model_result.framework})")
        sections.append("")

        if model_result.comparisons:
            sections.append(_build_metrics_table(model_result.comparisons))
            sections.append("")

        # Regression test result
        rr = model_result.regression_result
        sections.append(_build_regression_summary(rr))
        sections.append("")

        # Statistical details (collapsible for wilcoxon/bootstrap)
        stat_details = _build_statistical_details(rr)
        if stat_details:
            sections.append(stat_details)
            sections.append("")

    elif current_metrics:
        sections.append("### Current Metrics")
        sections.append("")
        sections.append(_build_current_metrics_table(current_metrics))
        sections.append("")

        baseline_mode = (baseline_source or {}).get("mode")
        if baseline_mode == "none":
            sections.append("_No baseline available. Reporting current metrics only._")
            sections.append("")

    coverage_current = current_only_metrics if current_only_metrics is not None else []
    coverage_baseline = baseline_only_metrics if baseline_only_metrics is not None else []
    if model_result:
        coverage_current = model_result.current_only_metrics
        coverage_baseline = model_result.baseline_only_metrics

    if coverage_current or coverage_baseline:
        sections.append("### Metric Coverage")
        sections.append("")
        if coverage_current:
            sections.append(
                f"- Current-only metrics: {', '.join(f'`{m}`' for m in coverage_current)}"
            )
        if coverage_baseline:
            sections.append(
                f"- Baseline-only metrics: {', '.join(f'`{m}`' for m in coverage_baseline)}"
            )
        sections.append("")

    # Data Quality section
    if data_result:
        sections.append("### Data Quality")
        sections.append("")
        sections.append(_build_data_quality_section(data_result))
        sections.append("")

    # Model Card section
    if model_card_path:
        sections.append("### Model Card")
        sections.append("")
        sections.append(f"Model card generated at `{model_card_path}`")
        sections.append("")

    # Summary
    sections.append("### Summary")
    sections.append("")
    if model_result:
        sections.append(f"- {model_result.summary}")
    if data_result:
        status = ":white_check_mark: Passed" if data_result.overall_passed else ":x: Failed"
        sections.append(f"- Data quality: {status}")
        if data_result.warning_count > 0:
            sections.append(f"- Data quality warnings: {data_result.warning_count}")
    sections.append("")

    # Footer
    sections.append("---")
    sections.append(f"*Generated by [ML-CI]({PROJECT_URL})*")

    return "\n".join(sections)


def _build_metrics_table(comparisons: list[MetricComparison]) -> str:
    """Build a GitHub-flavored markdown table from metric comparisons."""
    lines: list[str] = []
    lines.append("| Metric | Baseline | Current | Delta | Delta % | Status |")
    lines.append("|--------|----------|---------|-------|---------|--------|")

    for comp in comparisons:
        # Format values
        baseline_str = _fmt_metric(comp.baseline)
        current_str = _fmt_metric(comp.current)
        delta_str = _fmt_delta(comp.delta)
        pct_str = _fmt_pct(comp.delta_pct, comp.higher_is_better)

        # Status emoji
        if comp.regression and comp.severity == "fail":
            status = ":x:"
        elif comp.regression and comp.severity == "warn":
            status = ":warning:"
        elif comp.improved and comp.delta != 0:
            status = ":white_check_mark:"
        elif comp.delta == 0:
            status = ":heavy_minus_sign:"
        else:
            status = ":warning:"  # degraded but within tolerance

        lines.append(
            f"| {comp.name} | {baseline_str} | {current_str} | {delta_str} | {pct_str} | {status} |"
        )

    return "\n".join(lines)


def _build_current_metrics_table(metrics: dict[str, float]) -> str:
    """Build a simple markdown table for current-only reporting."""
    lines = [
        "| Metric | Current |",
        "|--------|---------|",
    ]
    for name, value in sorted(metrics.items()):
        lines.append(f"| {name} | {_fmt_metric(value)} |")
    return "\n".join(lines)


def _build_regression_summary(rr: Any) -> str:
    """Build a one-line regression test summary."""
    method = rr.method
    blocking_count = rr.details.get("blocking_regressed_count", rr.details.get("regressed_count", 0))
    warning_count = rr.details.get("warning_regressed_count", 0)
    if method == "threshold":
        tolerance = rr.details.get("tolerance")
        if tolerance is None:
            label = "**Regression test**: `threshold`"
        else:
            label = f"**Regression test**: `threshold` (default tolerance: {tolerance:.1%})"
    elif method == "wilcoxon":
        alpha = rr.details.get("alpha", 0.05)
        n = next(
            (v.get("n_observations", "?") for v in rr.details.get("metric_results", {}).values()),
            "?",
        )
        label = f"**Regression test**: `wilcoxon` (alpha: {alpha}, n={n} folds)"
    elif method == "bootstrap":
        conf = rr.details.get("confidence", 0.95)
        n_boot = rr.details.get("n_bootstrap", 10000)
        label = f"**Regression test**: `bootstrap` ({conf:.0%} CI, {n_boot} resamples)"
    else:
        label = f"**Regression test**: `{method}`"

    if blocking_count > 0 and warning_count > 0:
        result = (
            f"**Result**: :x: {blocking_count} blocking metric(s) regressed, "
            f"{warning_count} warning metric(s) regressed"
        )
    elif blocking_count > 0:
        result = f"**Result**: :x: {blocking_count} blocking metric(s) regressed"
    elif warning_count > 0:
        result = f"**Result**: :warning: {warning_count} warning metric(s) regressed"
    else:
        if method == "threshold":
            result = "**Result**: :white_check_mark: All metrics within tolerance"
        else:
            result = "**Result**: :white_check_mark: No statistically significant regression"

    return f"{label}\n{result}"


def _build_statistical_details(rr: Any) -> str | None:
    """Build a collapsible details block for statistical test results."""
    method = rr.method
    metric_results = rr.details.get("metric_results")
    if not metric_results or method == "threshold":
        return None

    lines: list[str] = []

    if method == "wilcoxon":
        alpha = rr.details.get("alpha", 0.05)
        lines.append(f"<details>\n<summary>Wilcoxon signed-rank test details (alpha = {alpha})</summary>\n")
        lines.append("| Metric | p-value | Median Diff | Significant | Regressed |")
        lines.append("|--------|---------|-------------|-------------|-----------|")
        for name, res in sorted(metric_results.items()):
            p = f"{res['p_value']:.4f}" if res["p_value"] < 1.0 else "1.0000"
            md = f"{res['median_diff']:+.4f}"
            sig = "Yes" if res["significant"] else "No"
            reg = ":x: Yes" if res["regressed"] else "No"
            lines.append(f"| {name} | {p} | {md} | {sig} | {reg} |")
        lines.append("\n</details>")

    elif method == "bootstrap":
        conf = rr.details.get("confidence", 0.95)
        n_boot = rr.details.get("n_bootstrap", 10000)
        lines.append(
            f"<details>\n<summary>Bootstrap CI details ({conf:.0%} confidence, {n_boot} resamples)</summary>\n"
        )
        lines.append("| Metric | Mean Diff | CI Lower | CI Upper | Regressed |")
        lines.append("|--------|-----------|----------|----------|-----------|")
        for name, res in sorted(metric_results.items()):
            md = f"{res['mean_diff']:+.4f}"
            lo = f"{res['ci_lower']:+.4f}"
            hi = f"{res['ci_upper']:+.4f}"
            reg = ":x: Yes" if res["regressed"] else "No"
            lines.append(f"| {name} | {md} | {lo} | {hi} | {reg} |")
        lines.append("\n</details>")

    return "\n".join(lines)


def _build_data_quality_section(data_result: DataValidationResult) -> str:
    """Build a data quality summary section."""
    lines: list[str] = []

    if data_result.filtered_columns:
        lines.append(
            "- Column scope: "
            + ", ".join(f"`{column}`" for column in data_result.filtered_columns[:8])
            + (" ..." if len(data_result.filtered_columns) > 8 else "")
        )

    if data_result.failures:
        lines.append("- :x: Blocking failures")
        for failure in data_result.failures[:5]:
            lines.append(f"  - {failure}")
    else:
        lines.append("- :white_check_mark: No blocking data-quality failures")

    if data_result.warnings:
        lines.append("- :warning: Non-blocking warnings")
        for warning in data_result.warnings[:5]:
            lines.append(f"  - {warning}")
    else:
        lines.append("- :white_check_mark: No non-blocking data-quality warnings")

    if data_result.missing_value_failures:
        lines.append("- Missing-value thresholds")
        for col, pct in sorted(data_result.missing_value_failures.items(), key=lambda item: -item[1])[:5]:
            threshold = data_result.missing_value_thresholds.get(col, 0.0)
            lines.append(f"  - `{col}`: {pct:.1%} missing (threshold {threshold:.1%})")
    elif data_result.missing_value_report:
        lines.append("- :white_check_mark: Missing-value thresholds respected")

    if data_result.label_distribution is not None:
        lines.append("- Label distribution")
        lines.append(f"  - Current `{data_result.label_column}`: {_format_label_distribution(data_result.label_distribution)}")
        if data_result.baseline_label_distribution is not None:
            lines.append(
                f"  - Baseline `{data_result.label_column}`: "
                f"{_format_label_distribution(data_result.baseline_label_distribution)}"
            )
        if data_result.label_distribution_shift:
            shifted = _format_label_shift(data_result.label_distribution_shift)
            lines.append(f"  - Share shift: {shifted}")

    guidance = data_result.details.get("guidance", [])
    if guidance:
        lines.append("- Helpful notes")
        for note in guidance[:5]:
            lines.append(f"  - {note}")

    return "\n".join(lines)


def _format_label_distribution(distribution: dict[str, int]) -> str:
    """Format a label distribution with counts and shares."""
    total = sum(distribution.values())
    parts: list[str] = []
    for label, count in sorted(distribution.items()):
        share = count / total if total else 0.0
        parts.append(f"`{label}`: {count} ({share:.1%})")
    return ", ".join(parts)


def _format_label_shift(shift: dict[str, float]) -> str:
    """Format label share deltas."""
    return ", ".join(
        f"`{label}` {delta:+.1%}"
        for label, delta in sorted(shift.items(), key=lambda item: (-abs(item[1]), item[0]))
    )


def _fmt_metric(value: float) -> str:
    """Format a metric value for display."""
    if abs(value) >= 1000:
        return f"{value:,.2f}"
    if abs(value) < 0.001 and value != 0:
        return f"{value:.2e}"
    return f"{value:.4f}"


def _fmt_delta(delta: float) -> str:
    """Format a delta value with +/- sign."""
    if delta == 0:
        return "0"
    sign = "+" if delta > 0 else ""
    return f"{sign}{_fmt_metric(delta)}"


def _fmt_pct(pct: float, higher_is_better: bool) -> str:
    """Format a percentage change."""
    if pct == 0:
        return "0%"
    if abs(pct) == float("inf"):
        return "N/A"
    sign = "+" if pct > 0 else ""
    return f"{sign}{pct:.1%}"


def post_or_update_comment(
    repo: str,
    pr_number: int,
    body: str,
    token: str,
) -> None:
    """Post a new PR comment or update an existing one.

    Searches for an existing comment containing COMMENT_MARKER to avoid
    flooding the PR with duplicate reports on re-runs.

    Args:
        repo: Repository in "owner/repo" format.
        pr_number: Pull request number.
        body: Markdown comment body.
        token: GitHub token with pull-requests:write permission.
    """
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    base_url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    # Search for existing ML-CI comment
    existing_comment_id = None
    page = 1
    while True:
        resp = requests.get(
            base_url,
            headers=headers,
            params={"per_page": 100, "page": page},
            timeout=30,
        )
        resp.raise_for_status()
        comments = resp.json()
        if not comments:
            break

        for comment in comments:
            if COMMENT_MARKER in comment.get("body", ""):
                existing_comment_id = comment["id"]
                break

        if existing_comment_id is not None:
            break
        page += 1

    # Update or create
    if existing_comment_id:
        url = f"https://api.github.com/repos/{repo}/issues/comments/{existing_comment_id}"
        resp = requests.patch(url, headers=headers, json={"body": body}, timeout=30)
        resp.raise_for_status()
        print(f"::notice::Updated existing ML-CI comment (id: {existing_comment_id})")
    else:
        resp = requests.post(base_url, headers=headers, json={"body": body}, timeout=30)
        resp.raise_for_status()
        print(f"::notice::Posted new ML-CI comment on PR #{pr_number}")


def get_pr_number() -> int | None:
    """Extract the PR number from the GitHub Actions event payload.

    Returns:
        PR number, or None if not running in a PR context.
    """
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path:
        return None

    try:
        with open(event_path) as f:
            event = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None

    # pull_request event
    if "pull_request" in event:
        return event["pull_request"].get("number")

    # issue_comment event (for /rerun type triggers)
    if "issue" in event and "pull_request" in event.get("issue", {}):
        return event["issue"].get("number")

    return None
